### ISSUE TITLE
buffering issue and slow downloads

### ISSUE THREAD

**Issue by kurokirasama** [iamtalhaasghar/yewtube#1]
Hello, 

there is a lot of buffering when streaming videos and downloads are very slow.

## Issue / Suggestion

For instance, a 40s video (7Mb) takes 100s. If i use set download_command "youtube-dl --external-downloader aria2c %u -o %F", it takes 20s.

A 12m video (99Mb) takes (36m), with aria2 it takes 9. 

I still trying to improve aria2 times.

My bandwidth is 300Mbps.

Downloading by other means take a few seconds (like JDownloader).

I read around that it might be a youtube-dl issue...??

Let me now if you need anything else.

## Your Environment

yewtube version      : 1.0.0
   notes           : released 14 October 2021
pafy version       : 0.5.5 (youtube-dl backend)
youtube-dl version : 2021.06.06
Python version     : 3.8.10 (default, Sep 28 2021, 16:10:42) 
[GCC 9.3.0]
Processor          : x86_64
Machine type       : x86_64
Architecture       : 64bit, ELF
Platform           : Linux-5.14.15-xanmod1-x86_64-with-glibc2.29
sys.stdout.enc     : utf-8
default enc        : utf-8
Config dir         : /home/kira/.config/mps-youtube
env:TERM           : xterm-256color
env:SHELL          : /bin/bash
env:LANG           : en_US.UTF-8

 
OS: Ubuntu 20.04.3 LTS x86_64 
Host: HP Pavilion Laptop 15-cs3xxx 
Kernel: 5.14.15-xanmod1 
Uptime: 22 mins 
Packages: 3612 (dpkg), 11 (snap) 
Shell: bash 5.0.17 
Resolution: 1920x1080 
DE: GNOME 
WM: Mutter 
WM Theme: RR-Jet -Black1.4v 
Theme: Black-n-White-GTK [GTK2/3] 
Icons: suru-plus-aspromauros-1.6 [GTK2/3] 
Terminal: guake 
CPU: Intel i7-1065G7 (8) @ 3.900GHz 
GPU: Intel Iris Plus Graphics G7 
GPU: NVIDIA GeForce GTX 1050 3 GB Max-Q 
Memory: 4660MiB / 11759MiB 

mpv 0.33.0 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on Thu Nov 26 06:59:44 UTC 2020
FFmpeg library versions:
   libavutil       56.60.100
   libavcodec      58.112.103
   libavformat     58.64.100
   libswscale      5.8.100
   libavfilter     7.90.100
   libswresample   3.8.100
FFmpeg version: git-2020-11-22-9208b72

**Comment by iamtalhaasghar** [comment]
Can you update to latest version and tell me if the problem still persists?
