### ISSUE TITLE
Encoding error on Windows

### ISSUE THREAD

**Issue by vicmortelmans** [iamtalhaasghar/yewtube#101]
I use yt on linux and on windows and only on windows I see this problem when a title contains strange characters:

## Issue / Suggestion
After playing a first item, e.g. from a playlist, no further items are played, the following error is displayed and I'm back at the yewtube prompt:

```
Problem playing last item: 'charmap' codec can't encode characters in position 12-14: character maps to <undefined>
```

The first item is always played correctly, it's only happening when automatically continuing with a next item in a selection or a list.

## Your Environment
Windows 10
Python 3.10.2
Yewtube 2.9.0

**Comment by Fatalon** [comment]
Recently (~1 week) I see a similar problem - previously I worked without any problem.

**Comment by Fatalon** [comment]
I dont know exactely why, but an update to 2.9 fixed my issue
