### ISSUE TITLE
Can't install the program

### ISSUE THREAD

**Issue by kiketson** [iamtalhaasghar/yewtube#104]
I just discovered this player, tried with mps-youtube and foudn out an error that couldn't be fixed. This is when I saw yewtube and I got stuck at the beginning.

Any help I can get?

Thank you!

pi@raspberrypi:~ $ pip install yewtube
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting yewtube
  Downloading https://files.pythonhosted.org/packages/e4/a7/037b3a2deb16124208aaa14b70ae874bc97ed32a6342f387406ca3152c05/yewtube-2.0.1.tar.gz (101kB)
    100% |████████████████████████████████| 102kB 162kB/s
    Complete output from command python setup.py egg_info:
    yewtube requires python 3.

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-z2Cc4J/yewtube/

pi@raspberrypi:~ $ mpsyt --version
mpsyt version      : 0.2.8
   notes           : released 17 February 2018
pafy version       : 0.5.5 (youtube-dl backend)
youtube-dl version : 2019.01.17
Python version     : 3.7.3 (default, Jul 25 2020, 13:03:44)
[GCC 8.3.0]
Processor          :
Machine type       : armv7l
Architecture       : 32bit, ELF
Platform           : Linux-5.4.83-v7l+-armv7l-with-debian-10.7
sys.stdout.enc     : UTF-8
default enc        : utf-8
Config dir         : /home/pi/.config/mps-youtube
env:TERM           : xterm
env:SHELL          : /bin/bash
env:LANG           : en_US.UTF-8
env:LANGUAGE       : en_US.UTF-8

**Comment by iamtalhaasghar** [comment]
It looks like you are trying to install yewtube with python2's pip. See the installation section of README.md and follow the recommended guidelines. Close the issue if it works.

**Comment by kiketson** [comment]
Python command wasn't using the right Python version. Fixed
