### ISSUE TITLE
[Feature Request] Subtitle support

### ISSUE THREAD

**Issue by ghost** [iamtalhaasghar/yewtube#108]
## Issue / Suggestion

It would be nice to have the option to show subtitles on videos that have them. From what i can tell my video player supports CC, but the option in mpv is greyed out even on videos that have them on youtube. 

I'm not sure how the new feature should work from a technical perspective; but if the user's video player supports displaying subtitles the user should be able to just use that video player's built in toggle. Maybe there could be a config setting in yewtube for preferred language(s), whether to include auto generated yt subtitles or only human made ones, and so on? But really anything at all will mean I can actually use this for watching videos.

## Your Environment

yewtube version 2.9.2, mpv version 0.34.1, linux mint 21.1. output from `yt --version` is:
```
yewtube version    : 2.9.2
yt_dlp version     : 2023.01.06
Python version     : 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0]
Processor          : x86_64
Machine type       : x86_64
Architecture       : 64bit, ELF
Platform           : Linux-5.15.0-58-generic-x86_64-with-glibc2.35
sys.stdout.enc     : utf-8
default enc        : utf-8
Config dir         : /home/mimuki/.config/mps-youtube
dbus               : None
glib               : False
env:TERM           : xterm-256color
env:SHELL          : /bin/bash
env:LANG           : en_AU.UTF-8
env:LANGUAGE       : en_AU:en
```

**Comment by iamtalhaasghar** [comment]
moving discussion to upstream repo https://github.com/mps-youtube/yewtube/issues/331
