### ISSUE TITLE
Search order (date) not respected

### ISSUE THREAD

**Issue by henkmet** [iamtalhaasghar/yewtube#109]
In mps-youtube I can set search order date in order to get the newest matches for a search instead of the most popular as the website serves. It seems now we are stuck with the search results from the website which makes this project essentially useless for me.

## Issue / Suggestion

If searching by date, I expect the newest videos that match the search terms.

## Your Environment

Arch linux. yewtube installed with pip

yewtube version    : 2.9.2
yt_dlp version     : 2022.11.11
Python version     : 3.10.9 (main, Dec 19 2022, 17:35:49) [GCC 12.2.0]

order             : date
user_order    : date

**Comment by iamtalhaasghar** [comment]
moved to https://github.com/mps-youtube/yewtube/issues/1206
