### ISSUE TITLE
[Crash] FileNotFoundError when starting on windows

### ISSUE THREAD

**Issue by rubenhorn** [iamtalhaasghar/yewtube#16]
## Issue / Suggestion
Running `yt` I get this error:
```
> yt
Traceback (most recent call last):
  File "C:\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Ruben\.local\bin\yt.exe\__main__.py", line 4, in <module>
  File "C:\Users\Ruben\.local\pipx\venvs\yewtube\lib\site-packages\mps_youtube\__init__.py", line 9, in <module>
    init.init()
  File "C:\Users\Ruben\.local\pipx\venvs\yewtube\lib\site-packages\mps_youtube\init.py", line 57, in init
    assign_player(config.PLAYER.get)  # Player is not assigned when config is loaded
  File "C:\Users\Ruben\.local\pipx\venvs\yewtube\lib\site-packages\mps_youtube\util.py", line 574, in assign_player
    g.PLAYER_OBJ = pl(player)
  File "C:\Users\Ruben\.local\pipx\venvs\yewtube\lib\site-packages\mps_youtube\players\mplayer.py", line 18, in __init__
    self.mplayer_version = _get_mplayer_version(player)
  File "C:\Users\Ruben\.local\pipx\venvs\yewtube\lib\site-packages\mps_youtube\players\mplayer.py", line 229, in _get_mplayer_version
    o = subprocess.check_output([exename]).decode()
  File "C:\Python310\lib\subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Python310\lib\subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Python310\lib\subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Python310\lib\subprocess.py", line 1435, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

## Your Environment
Shell: Microsoft Windows [Version 10.0.19043.1526] (cmd)
```
> pipx --version
1.0.0
```
```
> pipx list
venvs are in C:\Users\Ruben\.local\pipx\venvs
apps are exposed on your $PATH at C:\Users\Ruben\.local\bin
   package yewtube 22.2.15, installed using Python 3.10.2
    - yt.exe
```

**Comment by iamtalhaasghar** [comment]
have you tried `yt.exe`?

**Comment by rubenhorn** [comment]
Yes. It gives me the exact same output.

**Comment by rachmadaniHaryono** [comment]
i think it failed because it can't find executable on `exename` variable

i can try create pr to show exename when error, 

or if you run from source you can catch the exception and print exename value

**Comment by rubenhorn** [comment]
Turns out I forgot to install mplayer or mpv (VLC was installed but apparently it was not in my path).  
The code crashes [here](https://github.com/iamtalhaasghar/yewtube/blob/master/mps_youtube/util.py#L574).  
Maybe it's possible to detect that no player is present and gracefully exit?  
Even after installing mpv and adding VLC to the path it does only look for mplayer.

Also, after downloading a new build of mplayer it told me that I had to update it when I tried to start playback.  
I tracked down the issue to the version check [here] 
 (https://github.com/iamtalhaasghar/yewtube/blob/master/mps_youtube/players/mplayer.py#L28). The value of `ver` is `0dQw4w9WgXcQ; webm audio only; 1 Mb`.  
By just commenting out the `IOError` I was able to get it to work. (Playback suddenly stops mid song, but I think that is maybe an unrelated issue with Invidious)

My version of mplayer:
```
MPlayer Redxii-SVN-r38151-6.2.0 (x86_64) (C) 2000-2019 MPlayer Team
Using FFmpeg N-94664-g0821bc4eee (2019-08-26 16:09:11 -0700)
Compiled on 2019-08-28 01:29:43 EDT (rev. 1)
```

**Comment by rachmadaniHaryono** [comment]
i actually want to suggest using external library to search mpv like https://github.com/jaseg/python-mpv but mps-youtube/yewtube use custom mpv player https://github.com/iamtalhaasghar/yewtube/blob/master/mps_youtube/players/mpv.py

**Comment by rachmadaniHaryono** [comment]
> _get_mplayer_version

can you run the function? or maybe even debug it?

**Comment by rubenhorn** [comment]
Test code (copied from `_get_mplayer_version` and modified):
````python
import re, subprocess

exename = 'mplayer'
o = subprocess.check_output([exename]).decode()
# o = 'MPlayer Redxii-SVN-r38151-6.2.0 (x86_64) (C) 2000-2019 MPlayer Team...'
m = re.search('MPlayer SVN[\s-]r([0-9]+)', o, re.MULTILINE|re.IGNORECASE)

ver = 0
if m:
    ver = int(m.groups()[0])
else:
    m = re.search('MPlayer ([0-9])+.([0-9]+)', o, re.MULTILINE)
    if m:
        ver = tuple(int(i) for i in m.groups())

    else:
        print("no mplayer :(")

# Fixed regex
#  - extracts major
#  - extracts minor
#  - extracts optional patch
pattern = 'MPlayer \S*-([0-9]+)\.([0-9]+)(?:\.([0-9]+))? '
m = re.search(pattern, o, re.MULTILINE|re.IGNORECASE)
print(m.groups())
````

Outputs:
```
no mplayer :(
('6', '2', '0')
```

**Comment by rachmadaniHaryono** [comment]
actually the function should return 38151 and check if it is bigger than 37294

https://github.com/iamtalhaasghar/yewtube/blob/664ccd3d7ea773a122aaa676638375bc58f18909/mps_youtube/players/mplayer.py?rgh-link-date=2022-02-17T00%3A09%3A55Z#L30

**Comment by iamtalhaasghar** [comment]
> Maybe it's possible to detect that no player is present and gracefully exit? Even after installing mpv and adding VLC to the path it does only look for mplayer.

Yes, I have also experienced this, it does look for mplayer on first install and crashes even though i have set `vlc` as default player in `config.py` because most users have it on their system.


> Playback suddenly stops mid song

This happens only with mplayer mpv and vlc work fine. This is already a known bug. See #543

**Comment by rachmadaniHaryono** [comment]
#19 fix the version error but not FileNotFoundError maybe handle it on https://github.com/iamtalhaasghar/yewtube/blob/d2384e9da88a19610b6b16d2b072f8ceb80028f5/mps_youtube/players/mplayer.py#L18 ?
