### ISSUE TITLE
Recommending Colorama for Windows installs

### ISSUE THREAD

**Issue by AyoungDukie** [iamtalhaasghar/yewtube#34]
Just thought it would be a good idea to have a note in the documentation about adding Colorama on Windows systems to enable colors in the terminal.

## Issue / Suggestion

I have prepared a pull request here:
https://github.com/iamtalhaasghar/yewtube/pull/33
This would cover both an install with `pip` and for the recommended `pipx` installation methods.

**Comment by iamtalhaasghar** [comment]
Fixed in 9cf261615a52f6ac64b6fb28390db2a71a7ab470
