### ISSUE TITLE
Slow response when on VPN

### ISSUE THREAD

**Issue by jacksongoode** [iamtalhaasghar/yewtube#38]
I've found navigating the menu requires network requests to be made - even when opening the help menu with `h` takes 4-5 seconds on a VPN? This seems like a bug, but it always take ~1s off a VPN. I imagine this should involve a retooling of the help command but generally it might suggest sure to prioritizing menu responsiveness.

**Comment by rachmadaniHaryono** [comment]
i think there is this recent commit

https://github.com/iamtalhaasghar/yewtube/commit/d52b65d0c0cd8708020a2d6788102d82d8ebeee5

it may have effect because it require yewtube to download from github

**Comment by iamtalhaasghar** [comment]
Network requests are made only if you run any one of these two commands `help new` or `help tor` specifically. Rest of the menu commands don't make any network request. If you are saying the whole menu is sluggish then please be specific why do you think that is.

The goal of `help new` is to enable user to check change log of the latest available version (not the change log of the version he just installed).

**Comment by rachmadaniHaryono** [comment]
>> e: maybe i can try to refactor it to use local changelog instead downloading from github

> The goal of help new is to enable user to check change log of the latest available version (not the change log of the version he just installed).

ok, i will not create pr for that

i assume `help new` should show what user installed rather than latest entry on repo changelog

**Comment by jacksongoode** [comment]
>Network requests are made only if you run any one of these two commands help new or help tor specifically. Rest of the menu commands don't make any network request. If you are saying the whole menu is sluggish then please be specific why do you think that is.

It's weird if I break `Ctr-C` in the middle of a `help edit` or any other help edit I find Python in the middle of a request.
```
Traceback (most recent call last):
  File "/home/jackson/.local/bin/yt", line 8, in <module>
    sys.exit(main.main())
  File "/home/jackson/.local/lib/python3.10/site-packages/mps_youtube/main.py", line 154, in main
    if matchfunction(i.function, i.regex, userinput):
  File "/home/jackson/.local/lib/python3.10/site-packages/mps_youtube/main.py", line 69, in matchfunction
    func(*matches)
  File "/home/jackson/.local/lib/python3.10/site-packages/mps_youtube/commands/misc.py", line 44, in show_help
    g.content = get_help(choice)
  File "/home/jackson/.local/lib/python3.10/site-packages/mps_youtube/helptext.py", line 357, in get_help
    out, all_help = "", helptext()
  File "/home/jackson/.local/lib/python3.10/site-packages/mps_youtube/helptext.py", line 310, in helptext
    ("tor", "Check Tor Status. NOTE: Use this feature at your own risk. In case of any kind of damage we will not be responsible.", """{0}Tor Status{1}\n{3}""".format(c.ul, c.w, c.y, check_tor()))]
  File "/home/jackson/.local/lib/python3.10/site-packages/mps_youtube/helptext.py", line 391, in check_tor
    v = urlopen(url, timeout=1).read().decode()
  File "/usr/lib64/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/usr/lib64/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib64/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib64/python3.10/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/usr/lib64/python3.10/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib64/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib64/python3.10/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.10/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/usr/lib64/python3.10/http/client.py", line 975, in send
    self.connect()
  File "/usr/lib64/python3.10/http/client.py", line 1454, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/usr/lib64/python3.10/ssl.py", line 512, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib64/python3.10/ssl.py", line 1070, in _create
    self.do_handshake()
  File "/usr/lib64/python3.10/ssl.py", line 1341, in do_handshake
    self._sslobj.do_handshake()
KeyboardInterrupt
```

**Comment by iamtalhaasghar** [comment]
> > > e: maybe i can try to refactor it to use local changelog instead downloading from github
> 
> > The goal of help new is to enable user to check change log of the latest available version (not the change log of the version he just installed).
> 
> ok, i will not create pr for that
> 
> i assume `help new` should show what user installed rather than latest entry on repo changelog

Perhaps we can use `help changelog` for that. Feel free to create a pr for this.

**Comment by iamtalhaasghar** [comment]
> > Network requests are made only if you run any one of these two commands help new or help tor specifically. Rest of the menu commands don't make any network request. If you are saying the whole menu is sluggish then please be specific why do you think that is.
> 
> It's weird if I break `Ctr-C` in the middle of a `help edit` or any other help edit I find Python in the middle of a request.
> 
> ```
> Traceback (most recent call last):
>   File "/home/jackson/.local/bin/yt", line 8, in <module>
>     sys.exit(main.main())
>   File "/home/jackson/.local/lib/python3.10/site-packages/mps_youtube/main.py", line 154, in main
>     if matchfunction(i.function, i.regex, userinput):
>   File "/home/jackson/.local/lib/python3.10/site-packages/mps_youtube/main.py", line 69, in matchfunction
>     func(*matches)
>   File "/home/jackson/.local/lib/python3.10/site-packages/mps_youtube/commands/misc.py", line 44, in show_help
>     g.content = get_help(choice)
>   File "/home/jackson/.local/lib/python3.10/site-packages/mps_youtube/helptext.py", line 357, in get_help
>     out, all_help = "", helptext()
>   File "/home/jackson/.local/lib/python3.10/site-packages/mps_youtube/helptext.py", line 310, in helptext
>     ("tor", "Check Tor Status. NOTE: Use this feature at your own risk. In case of any kind of damage we will not be responsible.", """{0}Tor Status{1}\n{3}""".format(c.ul, c.w, c.y, check_tor()))]
>   File "/home/jackson/.local/lib/python3.10/site-packages/mps_youtube/helptext.py", line 391, in check_tor
>     v = urlopen(url, timeout=1).read().decode()
>   File "/usr/lib64/python3.10/urllib/request.py", line 216, in urlopen
>     return opener.open(url, data, timeout)
>   File "/usr/lib64/python3.10/urllib/request.py", line 519, in open
>     response = self._open(req, data)
>   File "/usr/lib64/python3.10/urllib/request.py", line 536, in _open
>     result = self._call_chain(self.handle_open, protocol, protocol +
>   File "/usr/lib64/python3.10/urllib/request.py", line 496, in _call_chain
>     result = func(*args)
>   File "/usr/lib64/python3.10/urllib/request.py", line 1391, in https_open
>     return self.do_open(http.client.HTTPSConnection, req,
>   File "/usr/lib64/python3.10/urllib/request.py", line 1348, in do_open
>     h.request(req.get_method(), req.selector, req.data, headers,
>   File "/usr/lib64/python3.10/http/client.py", line 1282, in request
>     self._send_request(method, url, body, headers, encode_chunked)
>   File "/usr/lib64/python3.10/http/client.py", line 1328, in _send_request
>     self.endheaders(body, encode_chunked=encode_chunked)
>   File "/usr/lib64/python3.10/http/client.py", line 1277, in endheaders
>     self._send_output(message_body, encode_chunked=encode_chunked)
>   File "/usr/lib64/python3.10/http/client.py", line 1037, in _send_output
>     self.send(msg)
>   File "/usr/lib64/python3.10/http/client.py", line 975, in send
>     self.connect()
>   File "/usr/lib64/python3.10/http/client.py", line 1454, in connect
>     self.sock = self._context.wrap_socket(self.sock,
>   File "/usr/lib64/python3.10/ssl.py", line 512, in wrap_socket
>     return self.sslsocket_class._create(
>   File "/usr/lib64/python3.10/ssl.py", line 1070, in _create
>     self.do_handshake()
>   File "/usr/lib64/python3.10/ssl.py", line 1341, in do_handshake
>     self._sslobj.do_handshake()
> KeyboardInterrupt
> ```

Now that`s something useful you have provided us.
