### ISSUE TITLE
Exception in thread Thread-4 (bindmpv):  KeyError: 'data'

### ISSUE THREAD

**Issue by jacksongoode** [iamtalhaasghar/yewtube#39]
Often when starting a video I receive this error, but it doesn't seem to affect the playback. A very similar error appears to happen on close `Ctrl-C`.

```
Exception in thread Thread-4 (bindmpv):                                                                               
Traceback (most recent call last):
  File "/usr/lib64/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jackson/.local/lib/python3.10/site-packages/mps_youtube/mpris.py", line 227, in bindmpv
    self.setproperty(resp['name'], resp['data'])
KeyError: 'data'
```

## Your Environment
Fedora 35, latest yewtube
```
yewtube version    : 2.7.0
yt_dlp version     : 2022.02.04
Python version     : 3.10.2 (main, Jan 17 2022, 00:00:00) [GCC 11.2.1 20211203 (Red Hat 11.2.1-7)]
Processor          : x86_64
Machine type       : x86_64
Architecture       : 64bit, ELF
Platform           : Linux-5.16.9-200.fc35.x86_64-x86_64-with-glibc2.34
sys.stdout.enc     : utf-8
default enc        : utf-8
Config dir         : /home/jackson/.config/mps-youtube
env:TERM           : xterm-256color
env:SHELL          : /usr/bin/zsh
env:LANG           : en_US.UTF-8
```

**Comment by iamtalhaasghar** [comment]
> Fedora 35, latest yewtube

We need to know exact version of yewtube you are running. Kindly paste output of `yt --version` and `mpv --version`.

**Comment by rachmadaniHaryono** [comment]
can this fixed by `resp.get('data')` instead of `resp['data']`?

**Comment by iamtalhaasghar** [comment]
> can this fixed by `resp.get('data')` instead of `resp['data']`?

Yes, but we need to know on which version of `mpv` this problem occurred because i use mpv and i haven't faced this issue ever. The closest ever thing to this was already patched in 7966a7a9178ecd3a87ae6dcb10f5fce45551d776.

**Comment by jacksongoode** [comment]
```
mpv 0.34.1 Copyright © 2000-2021 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
FFmpeg library versions:
   libavutil       56.70.100
   libavcodec      58.134.100
   libavformat     58.76.100
   libswscale      5.9.100
   libavfilter     7.110.100
   libswresample   3.9.100
FFmpeg version: 4.4.1
```

**Comment by rachmadaniHaryono** [comment]
as note this is on mpris module, so maybe there is more than that

if you run from source maybe print/debug what is on resp var

**Comment by rachmadaniHaryono** [comment]
https://github.com/iamtalhaasghar/yewtube/commit/834ed5b0af5f92e1233e8ba327327654f67f61a0 could raise error because https://github.com/iamtalhaasghar/yewtube/blob/834ed5b0af5f92e1233e8ba327327654f67f61a0/mps_youtube/mpris.py#L288

@iamtalhaasghar
