### ISSUE TITLE
only 100 videos are shown from playlists

### ISSUE THREAD

**Issue by JacobTempleton** [iamtalhaasghar/yewtube#45]
**Details**
Bug: The dump command doesn't load additional pages of playlists, it appears to only reload the first 2 pages, but doesn't show anything new.

1. Load a playlist with more than 2 pages [100 videos]
2. Type "dump"
3. No new videos load

**Environment**
yewtube version: 2.7.0
yt_dlp version: 2022.02.04
Python version: 3.9.5 (v3.9.5:0a7dcbdb13, May  3 2021, 13:17:02)
[Clang 6.0 (clang-600.0.57)]
Processor: i386
Machine type: x86_64
Architecture: 64bit,
Platform: macOS-10.16-x86_64-i386-64bit
sys.stdout.enc: utf-8
default enc: utf-8
Config dir: /Users/[user]/.config/mps-youtube
env:TERM: xterm-256color
env:SHELL: /bin/zsh
env:LANG: en_US.UTF-8

os: MacOS Monterey 12.2.1

**Comment by iamtalhaasghar** [comment]
`yewtube` shows all videos in a playlist by default and you can use `save` command to save entire contents of a playlist. So, i don't know what you were trying to accomplish with `dump` command. You need to paste the exact command here. Until then we'll consider the issue as resolved and `dump` command `deprecated`.

**Comment by JacobTempleton** [comment]
In that case, the issue is just that no more than 2 pages of videos show up in a playlist regardless of its length. For instance, take this playlist: https://www.youtube.com/playlist?list=PLbZIPy20-1pN7mqjckepWF78ndb6ci_qi (186 videos), only 2 pages (100 videos) are accessible. This is the same for any playlist that has more than 2 pages worth of videos, on the current version of MPS-Youtube you can just use "dump" and all pages will show which is what I tried doing here but nevertheless no more than 2 pages/100 videos can be seen. Saving, trying to go to a third+ page, nor dumping work to reveal/access more pages.
