### ISSUE TITLE
show [Safe for work] video thumbnails

### ISSUE THREAD

**Issue by SonaliBendre** [iamtalhaasghar/yewtube#46]
## Issue / Suggestion

sixel has the ability to show graphics/video/gif/image  in terminal

**Comment by iamtalhaasghar** [comment]
I think adding thumbnail support will do more harm than good as most of the times youtube thumbnails are misleading and serve only as a clickbait.

**Comment by iamtalhaasghar** [comment]
Effort is not worth it. Would require too much tweaking. Closing this issue again.

edit: so i did tried to implement this feature but its not feasible. See more detailed response here: https://github.com/mps-youtube/yewtube/issues/1196
