### ISSUE TITLE
can't download audio

### ISSUE THREAD

**Issue by loijunator** [iamtalhaasghar/yewtube#50]
ffmpeg is installed and is working properly, but encoding isnt working for mp4 or m4a

I havent made any changes to the ~/.config/mps-youtube/transcode file. Everytime i enter the "da 1" command to download audio, it downloads a .webm 
 Environment:
yewtube version : v2202.16.3

**Comment by rachmadaniHaryono** [comment]
try install new version 2.8.0 and check if the same issue exist

**Comment by KwisatzJim** [comment]
this is happening for me as well. 
set:
 audio_format      : auto
 video_format      : mp4
but output is still webm

version = 2.8.5 (2022-09-08)

**Comment by aldrinjenson** [comment]
same issue in 2.9
Can't download audio
