### ISSUE TITLE
How do I make yewtube respects my mpv configuration?

### ISSUE THREAD

**Issue by jvschiavo** [iamtalhaasghar/yewtube#51]
First of all, thanks for the amazing software.
## Issue / Suggestion

When it opens a video with mpv, the player uses default input, and doesn't respect my `~/.config/mpv/input.conf` and `~/.config/mpv/mpv.conf` files.

I did `set show_video true`, then tried to play any video by searching and entering a number.

## Your Environment

```
OS: Debian 11 bullseye
Kernel: x86_64 Linux 5.10.0-11-amd64
```

`bash: mpsyt: command not found`
Although `yt --version` returns:
```
yewtube version    : 2.8.0
yt_dlp version     : 2022.02.04
Python version     : 3.9.2 (default, Feb 28 2021, 17:03:44) 
[GCC 10.2.1 20210110]
Processor          : 
Machine type       : x86_64
Architecture       : 64bit, ELF
Platform           : Linux-5.10.0-11-amd64-x86_64-with-glibc2.31
sys.stdout.enc     : utf-8
default enc        : utf-8
Config dir         : /home/my_user/.config/mps-youtube
env:TERM           : xterm-256color
env:SHELL          : /bin/bash
env:LANG           : pt_BR.UTF-8
```

Debian 11 bullseye

mpv 0.32.0

**Comment by iamtalhaasghar** [comment]
> the player uses default input and Doesn't respect my mpv config

Can you give some more explanation?

**Comment by jvschiavo** [comment]
> Can you give some more explanation?

Sure. Actually, after some more testing, I've realized that yt considers the content of my `~/.config/mpv/mpv.conf` when it opens mpv. That means that if I have some lines like:
```
keep-open=yes
osc=no
ontop=yes
volume-max=250
```
those configurations are respected by the mpv player invoked through yt, but it contrast, it doesn't respect the custom inputs I've configured in my `~/.config/mpv/input.conf` file. So even if I have changed the behavior of the UP arrow to `add volume 10` instead of `seek 60` the mpv player invoked by yt doesn't respect that change.

**Comment by rachmadaniHaryono** [comment]
based on this yewtube use its own custom input to play with mpv

https://github.com/iamtalhaasghar/yewtube/blob/d7fa4e914d138152f2e1ee92726a18d46f3f144b/mps_youtube/players/mpv.py#L274

i don't know if it is better to merge it with user custom input

**Comment by jvschiavo** [comment]
Is there a way to make it use the default `~/.config/mpv/input.conf` file instead? I'm not experienced with python.

**Comment by rachmadaniHaryono** [comment]
quick fix is to replace this line with full path of your mpv input conf

https://github.com/iamtalhaasghar/yewtube/blob/d7fa4e914d138152f2e1ee92726a18d46f3f144b/mps_youtube/players/mpv.py#L281

```python
confpath = 'home/yourusername/.config/mpv/input.conf'
```

second option is to copy your mpv `input.conf` to yewtube mpv input config

```shell
cp ~/.config/mpv/input.conf ~/.config/mps-youtube/mpv-input.conf
```

yewtube will still replace the config with its own config, so check if there is any conflict
