### ISSUE TITLE
userpl not working properly

### ISSUE THREAD

**Issue by Aneeqasif** [iamtalhaasghar/yewtube#53]
## Issue / Suggestion

- userpl option is just showing the videos instead of playlists by user
-  there is ? instead of view count in view count column

and thanks for maintaining this fork plz look at this issues , 
have a great day :)

## Your Environment
yewtube version    : 2.8.0
yt_dlp version     : 2022.02.04
Python version     : 3.10.2 (main, Jan 15 2022, 19:56:27) [GCC 11.1.0]
Processor          : 
Machine type       : x86_64
Architecture       : 64bit, ELF
Platform           : Linux-5.12.19-1-MANJARO-x86_64-with-glibc2.33
sys.stdout.enc     : utf-8
default enc        : utf-8
Config dir         : /home/aneeq/.config/mps-youtube
env:TERM           : xterm-256color
env:SHELL          : /usr/bin/zsh
env:LANG           : en_US.UTF-8
player -> mpv

**Comment by kurokirasama** [comment]
hello, I would like to know if this has hope of fixing or it would be difficult...

**Comment by iamtalhaasghar** [comment]
We need to add this functionality to `youtube-search-python`, the library on which `yewtube` depends upon.
