### ISSUE TITLE
lets port cool features from projects similar to yewtube

### ISSUE THREAD

**Issue by Aneeqasif** [iamtalhaasghar/yewtube#55]
## Issue / Suggestion
many features are not working here because of ditching youtube api (like playlist scrapping , view count etc etc) , there is another program ytfzf these guyz are also achieving pretty much the same may be we can use their ideas to improve our project
https://github.com/pystardust/ytfzf

**Comment by iamtalhaasghar** [comment]
Yeah, we will try to take advantage of `ytfzf` as much as we can.

**Comment by Aneeqasif** [comment]
any new stuff dude?
