### ISSUE TITLE
Yewtube returns only 10 entries after a search

### ISSUE THREAD

**Issue by Thomasorus** [iamtalhaasghar/yewtube#6]
## Issue / Suggestion

Before version 1.1.0, yewtube returned more than 10 entries. Now it returns only ten.
![Capture d’écran 2022-01-28 à 17 24 06](https://user-images.githubusercontent.com/8302525/151584984-841e0135-a16f-464f-89a0-a201a4aa2e3f.png)

## Your Environment
Player: MPV

Version:

```
yewtube version      : 1.1.0
   notes           : released on 28 Jan 2022
youtube-dl version : 2021.12.17
Python version     : 3.9.10 (main, Jan 15 2022, 11:40:53)
[Clang 13.0.0 (clang-1300.0.29.3)]
Processor          : arm
Machine type       : arm64
Architecture       : 64bit,
Platform           : macOS-12.1-arm64-arm-64bit
sys.stdout.enc     : utf-8
default enc        : utf-8
Config dir         : /Users/thomasperso/.config/mps-youtube
env:TERM           : xterm-256color
env:SHELL          : /bin/zsh
env:LANG           : fr_FR.UTF-8
```

Thanks for your work!

**Comment by iamtalhaasghar** [comment]
Because i removed youtube api, now you can not move back and forth on search result pages. So for now, How many entries should be shown by default? 10, 20 or 30?

**Comment by Thomasorus** [comment]
I would say 30 if you can? It's like a full page of text on a classic 1080p screen, that's great. I sometimes need to find music that is not in the top 10 or 20.

Also we can still use our own api key and move back and forth? If yes, maybe documenting it in the readme could be a good idea.

**Comment by iamtalhaasghar** [comment]
I just found that we can't have more than 20 results without youtube api. For now I have set the upper limit of search results to **50**. And you can move back and forth as well in search result pages as well.
