### ISSUE TITLE
can't detect player using playerctl

### ISSUE THREAD

**Issue by cevhyruz** [iamtalhaasghar/yewtube#61]
I'm usually running this app in the background and using playerctl to control it and many more like getting metadata.
Now even if I list available mpris player using `playerctl --list-all` nothing shows up.

## Your Environment

yewtube version    : 2.8.1
yt_dlp version     : 2022.02.04
Python version     : 3.8.0 (default, Mar  6 2022, 19:23:28)
[GCC 11.2.0]
Processor          :
Machine type       : x86_64
Architecture       : 64bit, ELF
Platform           : Linux-5.16.0-3-amd64-x86_64-with-glibc2.2.5
sys.stdout.enc     : utf-8
default enc        : utf-8
Config dir         : /home/devs/.config/mps-youtube
env:TERM           : xterm-256color
env:SHELL          : /bin/bash
env:LANG           : C.UTF-8

**Comment by rachmadaniHaryono** [comment]
do you install it with mpris extra? for example `pipx install yewtube[mpris]`

**Comment by cevhyruz** [comment]
> do you install it with mpris extra? for example pipx install yewtube[mpris]

didn't actually install anything, python newbie here. how can I install it?

**Comment by rachmadaniHaryono** [comment]
> didn't actually install anything

can you explain more? how do you install yewtube in the first place? do you use pip, pipx, etc?

**Comment by cevhyruz** [comment]
I only install yewtube using `pip` not `pipx`. now trying to reinstall using pipx

**Comment by cevhyruz** [comment]
I only install yewtube using `pip` not `pipx`. now trying to reinstall using pipx

**Comment by cevhyruz** [comment]
Still not working. There is one player showing up though, `chromium.instance321744` i doubt this is the player for yewtube, is it?

**Comment by rachmadaniHaryono** [comment]
```shell
> playerctl -l
mps-youtube.instance567867
```
that should be the result

what is the result of `pipx list --include-injected`

**Comment by cevhyruz** [comment]
> what is the result of pipx list --include-injected

Here it is..
venvs are in /home/devs/.local/pipx/venvs
apps are exposed on your $PATH at /home/devs/.local/bin
   package yewtube 2.8.1, installed using Python 3.8.0
    - yt

**Comment by rachmadaniHaryono** [comment]
on mpris what is the result of `set`?

```shell
  Key                 Value
  order             : relevance
  user_order        :
  max_res           : 2160p
  player            : mpv
  playerargs        :
  encoder           : 0 [None]
  notifier          :
  checkupdate       : True
  show_player_keys  : True
  fullscreen        : False
  show_status       : True
  always_repeat     : False
  columns           : user date comments views
  ddir              : /mnt/ac54dceb-73a5-4f94-b52c-cb7a426c0f29/Downloads/mps
  overwrite         : True
  show_video        : False
  search_music      : False
  window_pos        :
  window_size       :
  download_command  :
  lookup_metadata   : True
  lastfm_username   :
  lastfm_password   :
  lastfm_api_key    :
  lastfm_api_secret :
  audio_format      : auto
  video_format      : auto
  pages             : 3
  autoplay          : False
  set_title         : True
  mpris             : True
  show_qrcode       : False
  history           : True
  input_history     : True
  vlc_dummy_interface : False

Enter set <key> <value> to change
Enter set all default to reset all
```
maybe `set mpris true`?

**Comment by cevhyruz** [comment]
```
  Key                 Value
  order             : relevance
  user_order        :
  max_res           : 360p
  player            : mplayer
  playerargs        :
  encoder           : 0 [None]
  notifier          :
  checkupdate       : True
  show_player_keys  : True
  fullscreen        : False
  show_status       : True
  always_repeat     : False
  columns           : date user
  ddir              : /home/devs/Downloads/mps
  overwrite         : True
  show_video        : False
  search_music      : True
  window_pos        :
  window_size       :
  download_command  :
  lookup_metadata   : True
  lastfm_username   :
  lastfm_password   :
  lastfm_api_key    :
  lastfm_api_secret :
  audio_format      : auto
  video_format      : auto
  pages             : 3
  autoplay          : True
  set_title         : True
  mpris             : True
  show_qrcode       : False
  history           : True
  input_history     : True

  vlc_dummy_interface : False

Enter set <key> <value> to change
Enter set all default to reset all
>
```
Mpris is set to True. also I have reinstalled `yt` using the recommended way on README (the pipx one).

> pipx install yewtube[mpris]
I have tried using this but returns 'no match'

**Comment by rachmadaniHaryono** [comment]
```shell
> pipx install yewtube[mpris]
zsh: no matches found: yewtube[mpris]
> pipx install 'yewtube[mpris]'
  installed package yewtube 2.8.1, installed using Python 3.9.7
  These apps are now globally available
    - yt
done! ✨ 🌟 ✨
```
try put it on quote

**Comment by cevhyruz** [comment]
> pipx install 'yewtube[mpris]'
This one solve it! Thank you for the fast response. I think this should be noted on README too.

**Comment by rachmadaniHaryono** [comment]
i will create pr for this later

 basically

- doc on mpris install
- dbus, pyglib check on version info
