### ISSUE TITLE
How do I go to the next page?

### ISSUE THREAD

**Issue by erikrios** [iamtalhaasghar/yewtube#62]
## Your Environment

Hi, sir. I wanna ask.

How do I go to the next page?

Thank you.
![Screenshot_2022-03-10-09-42-17-40_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/42199285/157578281-0a7fe72e-71a2-42bf-9fdf-13cd5b012ac7.jpg)

**Comment by rachmadaniHaryono** [comment]
`n`

**Comment by erikrios** [comment]
Thank you @rachmadaniHaryono
