### ISSUE TITLE
"Webm audio only: 1 Mb" - player stops in the middle of the song and jumps to the next

### ISSUE THREAD

**Issue by mejwen** [iamtalhaasghar/yewtube#71]
Whenever I play any song, the player stops and go to the next song. Even if I change audio_format, the song is stuck on webm.

## Issue / Suggestion
1. Look for any song /songname
2. Type "1-"
3. Wait a while (about 1min)
3. The player stops and go to the next song.

## Your Environment
yewtube version    : 2.8.3
yt_dlp version     : 2022.04.08
Python version     : 3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)]
Processor          : Intel64 Family 6 Model 142 Stepping 10, GenuineIntel
Machine type       : AMD64
Architecture       : 64bit, WindowsPE
Platform           : Windows-10-10.0.19043-SP0
sys.stdout.enc     : utf-8
default enc        : utf-8
dbus               : None
glib               : False

**Comment by iamtalhaasghar** [comment]
See #70
