### ISSUE TITLE
Video pops up even if I set show_video to false

### ISSUE THREAD

**Issue by mejwen** [iamtalhaasghar/yewtube#76]
## Issue / Suggestion
When the song starts, the video pops up sometimes. Its weird, because I have set show_video variable to false in my config.

![image](https://user-images.githubusercontent.com/104422037/168430729-6bddd089-d9dc-4039-a398-ecb6012fac95.png)

![image](https://user-images.githubusercontent.com/104422037/168430752-eccabae9-1cfe-428a-b323-807349899542.png)

## Your Environment

**Yewtube**

yewtube version    : 2.8.3
yt_dlp version     : 2022.04.08
Python version     : 3.10.4 (main, Apr  2 2022, 09:04:19) [GCC 11.2.0]
Processor          : x86_64
Machine type       : x86_64
Architecture       : 64bit, ELF
Platform           : Linux-5.17.5-76051705-generic-x86_64-with-glibc2.35
sys.stdout.enc     : utf-8
default enc        : utf-8
Config dir         : /home/xelot/.config/mps-youtube
dbus               : 1.2.18
glib               : True
env:TERM           : xterm-256color
env:SHELL          : /bin/bash
env:LANG           : en_US.UTF-8

**OS**

Operating System: Pop!_OS 22.04 LTS               
          Kernel: Linux 5.17.5-76051705-generic
    Architecture: x86-64

**Music player**

mpv 0.34.1 Copyright © 2000-2021 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
FFmpeg library versions:
   libavutil       56.70.100
   libavcodec      58.134.100
   libavformat     58.76.100
   libswscale      5.9.100
   libavfilter     7.110.100
   libswresample   3.9.100
FFmpeg version: 4.4.1-3ubuntu5

**Comment by kolubczynski** [comment]
Searching videos and albums worked fine (/ //), but when we chose " u <number> - show videos uploaded by uploader of video <number>"  and we will try to play something then the music player is open (mpv or vlc) in a new window. 
Example
/music 
u 1
1

and for some reasons the vlc pops up, but when I will open the video directly (from first search or via link etc. is okay)

**Comment by frojnd** [comment]
I can reproduce this with 2.8.4 for certain playlists

Steps to reproduce:

Search playlists: //foo
Choose range 1-10
Video pops up in mpv

**Comment by bvvt** [comment]
This is happening to me too, MPV pops for some videos regardless of video being disabled.

**Comment by kehkuansun** [comment]
Try `set playerargs --no-video` to let mpv know you don't want the video. It worked for me.

**Comment by bvvt** [comment]
@kehkuansun 
> Try `set playerargs --no-video` to let mpv know you don't want the video. It worked for me.

How do i quickly override it if want to play one _with_ video?

**Comment by marcomeyerVFX** [comment]
I think this commit https://github.com/iamtalhaasghar/yewtube/commit/eaeff58f94e2fd89706e42fdab6b8e82ef770941 disregards the `-v` override that used to work when `show_video` was set to `False`. I'm not very immersed in the code of this project, but looks like an additional quick check against `self.override` before setting the playerarg might help (just guessing)
