### ISSUE TITLE
using poetry

### ISSUE THREAD

**Issue by rachmadaniHaryono** [iamtalhaasghar/yewtube#8]
i want to run it on poetry but found several issue

first i generated pyproject using

https://github.com/CircleOnCircles/dephell

and edited it until it work

<details><summary>generated pyproject</summary>
<p>

```toml
[tool]
[tool.poetry]
name = "yewtube"
version = "1.1.4"
description = "A Terminal based YouTube player and downloader. No Youtube API key required. Forked from mps-youtube"
license = "GPLv3"
keywords = [
  "video",
  "music",
  "audio",
  "youtube",
  "stream",
  "download",
]
classifiers = [
  "Topic :: Utilities",
  "Topic :: Internet :: WWW/HTTP",
  "Topic :: Multimedia :: Sound/Audio :: Players",
  "Topic :: Multimedia :: Video",
  "Environment :: Console",
  "Environment :: Win32 (MS Windows)",
  "Environment :: MacOS X",
  "Operating System :: POSIX :: Linux",
  "Operating System :: MacOS",
  "Operating System :: MacOS :: MacOS 9",
  "Operating System :: MacOS :: MacOS X",
  "Operating System :: Microsoft",
  "Operating System :: Microsoft :: Windows :: Windows 7",
  "Operating System :: Microsoft :: Windows :: Windows XP",
  "Operating System :: Microsoft :: Windows :: Windows Vista",
  "Intended Audience :: End Users/Desktop",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.3",
  "Programming Language :: Python :: 3.4",
  "Programming Language :: Python :: 3 :: Only",
  "Development Status :: 5 - Production/Stable",
  "License :: OSI Approved :: GNU General Public License v3 (GPLv3)"
]
homepage = "https://github.com/iamtalhaasghar/yewtube"
authors = ["talha_programmer <talhaasghar.contact@simplelogin.fr>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "*"
pyperclip = "*"
pyreadline = "*"
youtube-search-python = "*"
yt-dlp = "*"
```

</p>
</details>

working pyproject

```toml
[tool]
[tool.poetry]
name = "yewtube"
version = "1.1.4"
description = "A Terminal based YouTube player and downloader. No Youtube API key required. Forked from mps-youtube"
license = "GPLv3"
keywords = [
  "video",
  "music",
  "audio",
  "youtube",
  "stream",
  "download",
]
classifiers = [
  "Topic :: Utilities",
  "Topic :: Internet :: WWW/HTTP",
  "Topic :: Multimedia :: Sound/Audio :: Players",
  "Topic :: Multimedia :: Video",
  "Environment :: Console",
  "Environment :: Win32 (MS Windows)",
  "Environment :: MacOS X",
  "Operating System :: POSIX :: Linux",
  "Operating System :: MacOS",
  "Operating System :: MacOS :: MacOS 9",
  "Operating System :: MacOS :: MacOS X",
  "Operating System :: Microsoft",
  "Operating System :: Microsoft :: Windows :: Windows 7",
  "Operating System :: Microsoft :: Windows :: Windows XP",
  "Operating System :: Microsoft :: Windows :: Windows Vista",
  "Intended Audience :: End Users/Desktop",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.3",
  "Programming Language :: Python :: 3.4",
  "Programming Language :: Python :: 3 :: Only",
  "Development Status :: 5 - Production/Stable",
  "License :: OSI Approved :: GNU General Public License v3 (GPLv3)"
]
homepage = "https://github.com/iamtalhaasghar/yewtube"
authors = ["talha_programmer <talhaasghar.contact@simplelogin.fr>"]
readme = "README.md"
packages=[
{include = 'mps_youtube'},
{include = 'mps_youtube/commands'},
{include = 'mps_youtube/listview'},
{include = 'mps_youtube/players'},
]

[tool.poetry.dependencies]
python = ">=3.6"
pyperclip = "^1.8.2"
youtube-search-python = "^1.6.2"
yt-dlp = "^2022.2.4"
pyreadline3 = {version = "^3.4.1", platform = "win32"}

[tool.poetry.scripts]
yt = 'mps_youtube:main.main'
```

## Issue / Suggestion

- on setup.py it only require python3, but based on working pyproject it require minimum python3.6
  - as note python3.6 security support end last december https://endoflife.date/python
- pyreadline last update is 2015 and it only support windows
  - use pyreadline3 https://github.com/pyreadline3/pyreadline3 and restrict it to windows, pypi last release jan 25 2022 https://pypi.org/project/pyreadline3/

## Your Environment

```shell
> poetry run yt --version
yewtube version    : 1.1.4 released on 10 Feb 2022
yt_dlp version     : 2022.02.04
Python version     : 3.9.7 (default, Nov  7 2021, 15:17:57)
[GCC 11.2.0]
Processor          : x86_64
Machine type       : x86_64
Architecture       : 64bit, ELF
Platform           : Linux-5.13.0-28-generic-x86_64-with-glibc2.34
sys.stdout.enc     : utf-8
default enc        : utf-8
Config dir         : /home/r3r/.config/mps-youtube
env:TERM           : tmux-256color
env:SHELL          : /usr/bin/zsh
env:LANG           : en_US.UTF-8
> git rev-parse --short HEAD
d6a485e
```

**Comment by iamtalhaasghar** [comment]
As `pip` and  `pipx` gets the job done for us so we really don't need `poetry`.

**Comment by rachmadaniHaryono** [comment]
it is not about replacing setup.py with poetry but the requirement on setup.py based on poetry 

see

> - on setup.py it only require python3, but based on working pyproject it require minimum python3.6
>    - as note python3.6 security support end last december [endoflife.date/python](https://endoflife.date/python)
> - pyreadline last update is 2015 and it only support windows
>    - use pyreadline3 [pyreadline3/pyreadline3](https://github.com/pyreadline3/pyreadline3) and restrict it to windows, pypi last release jan 25 2022 [pypi.org/project/pyreadline3](https://pypi.org/project/pyreadline3/)

**Comment by iamtalhaasghar** [comment]
> it is not about replacing setup.py with poetry but the requirement on setup.py based on poetry
> 
> see
> 
> > * on setup.py it only require python3, but based on working pyproject it require minimum python3.6
> >   
> >   * as note python3.6 security support end last december [endoflife.date/python](https://endoflife.date/python)
> > * pyreadline last update is 2015 and it only support windows
> >   
> >   * use pyreadline3 [pyreadline3/pyreadline3](https://github.com/pyreadline3/pyreadline3) and restrict it to windows, pypi last release jan 25 2022 [pypi.org/project/pyreadline3](https://pypi.org/project/pyreadline3/)

dear i know, what i am saying is i don't have time to make `setup.py` compatible with `poetry`. If you want, do it create a pull request and i'll happily merge.

**Comment by iamtalhaasghar** [comment]
May be in future we'll work on this once we successfully get rid of Youtube API v3 with all features working.

**Comment by rachmadaniHaryono** [comment]
pr created

i just found out that there  is issue https://github.com/iamtalhaasghar/yewtube/issues/10, which could be fixed if pyreadline is replaced with pyreadline3

> May be in future we'll work on this once we successfully get rid of Youtube API v3 with all features working.

maybe replace it with invirdious api? 

https://github.com/mps-youtube/mps-youtube/issues/1119

https://docs.invidious.io/API.md

**Comment by rachmadaniHaryono** [comment]
not necessarily, the goal is just to get necessary data which previous getting from pafy and not yet covered by yt-dlp

i just see another problem

- choosing invidious instance, we could use https://api.invidious.io/ . it have api
- cache result from invidious

**Comment by iamtalhaasghar** [comment]
The current codebase is dependent on response / json data returned by youtube api v3. The reason why `yewtube` is working is that we are using `yt-dlp` and `youtube-search-python`. Both of these tool scrap the data from YouTube and the json / response you get is similar as if we used Youtube API v3.
On the other hand, individious has totally different response / json schema for api calls.
It is possible to use invidious as a backend for yewtube but it would require major code refactoring.
