### ISSUE TITLE
error when try to add args to player

### ISSUE THREAD

**Issue by kurokirasama** [iamtalhaasghar/yewtube#90]
I'm using mpv as the player, and I'm trying to set `playerargs` to `--no-border`. My attempts are
```
yt set player mpv, set playerargs --no-border
yt set player mpv, set playerargs '--no-border'
yt set player mpv, set playerargs "--no-border"
```

In any case I got:
```
yt: error: unrecognized arguments: -no-border
```

## Issue / Suggestion

can't set playerargs for mpv

## Your Environment

yewtube version    : 2.8.4
yt_dlp version     : 2022.02.04
Python version     : 3.8.10 (default, Jun 22 2022, 20:18:18) 
[GCC 9.4.0]
Processor          : x86_64
Machine type       : x86_64
Architecture       : 64bit, ELF
Platform           : Linux-5.18.18-xanmod1-x86_64-with-glibc2.29
sys.stdout.enc     : utf-8
default enc        : utf-8
Config dir         : /home/kira/.config/mps-youtube
dbus               : 1.2.16
glib               : True
env:TERM           : xterm-256color
env:SHELL          : /home/kira/.cargo/bin/nu
env:LANG           : en_US.UTF-8

Ubuntu 20.04.4 LTS x86_64 

mpv 0.33.0

**Comment by iamtalhaasghar** [comment]
`set playerargs --no-border` works inside yt.

**Comment by kurokirasama** [comment]
> `set playerargs --no-border` works inside yt.

so it is not posible from the outside?

**Comment by iamtalhaasghar** [comment]
If u want do a pull request and i'll merge it happily.
