### ISSUE TITLE
Add a repeat functionality

### ISSUE THREAD

**Issue by fazlizekiqi** [iamtalhaasghar/yewtube#92]
**Sugggestion**
Add a repeat command "r" where we can essentially repeat music that we stream.

**Comment by iamtalhaasghar** [comment]
We already have a similar functionality.
https://github.com/iamtalhaasghar/yewtube/blob/18b306fd51e89d1a0d42f4214db18a490e1bde85/mps_youtube/helptext.py#L230

**Comment by fazlizekiqi** [comment]
Great thanks.
