### ISSUE TITLE
Search result not sorted by order setting

### ISSUE THREAD

**Issue by Omaeda** [iamtalhaasghar/yewtube#94]
order settings are not being applied to search results

## Issue 
As an example I have changed the order configuration from relevance to views with the command:
`set order views`
After that I looked for a video, but the order in which they were presented was still the same as before changing the configuration.

## Your Environment
```
$ yt --version
yewtube version    : 2.8.5
yt_dlp version     : 2022.08.08
Python version     : 3.9.12 (main, Apr  5 2022, 06:56:58)
[GCC 7.5.0]
Processor          : x86_64
```

**Comment by iamtalhaasghar** [comment]
moving discussion to https://github.com/mps-youtube/yewtube/issues/1206
