### ISSUE TITLE
[Feature Request] Package for debian/ubuntu

### ISSUE THREAD

**Issue by lonix1** [iamtalhaasghar/yewtube#95]
Currently this (excellent) fork is only installable via python.

It would be nice:
- to have this in the debian/ubuntu `apt` package manager, OR
- to have a `.deb` binary file in the releases page

The upstream does both, maybe it's something that can be copy-pasted? (I wouldn't know for sure). At the very least, a `.deb` would be nice (keep in mind it's just the build output, and the upstream probably does it in a build script.)

**Comment by iamtalhaasghar** [comment]
Related to #82
